# Generated by Django 4.2 on 2023-04-28 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('operations', '0003_operation_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation_response', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.operation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
