# Generated by Django 4.2 on 2023-04-29 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_balance'),
        ('records', '0002_remove_record_user_record_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
