# Generated by Django 4.2 on 2023-04-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_rename_operations_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
